### ISSUE TITLE
Probably not required anymore?

### ISSUE THREAD

**Issue by wodCZ** [alloc/vite-plugin-legacy#14]
Hi.

I was in need of IE11 support and I found [this issue](https://github.com/vitejs/vite/issues/779), which led me to this plugin.

After dozens of minutes I've aborted the mission with no success (blank page in IE11, not even an error). Today I've revisited the problem and found that there is an official plugin: [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy).

Replacing this one with the official one fixed the issue (well, expect for another small [issue](https://github.com/vitejs/vite/issues/2442)) and the devil users of IE11 can access the app now.

To be clear - I'm thankful for the effort you put in this ❤️  but maybe, you would consider adding a link to the official plugin to the readme? It could've saved me some time & struggles.

Thanks!

**Comment by aleclarson** [comment]
👍
