### ISSUE TITLE
Error: Unhandled promise rejection ReferenceError: 'regeneratorRuntime' is undefined

### ISSUE THREAD

**Issue by joshdura** [alloc/vite-plugin-legacy#15]
When running @vitejs/plugin-legacy, I get the following error in IE11:

```
Unhandled promise rejection ReferenceError: 'regeneratorRuntime' is undefined
```

Looking around online, it looks like adding [@babel/plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) will fix this. I tried adding a .babelrc with this plugin to my root, but it doesn't seem to pick it up. Is there any way to pass this through to the plugin?

**Comment by aleclarson** [comment]
Are you using `corejs: true`?

This plugin imports `regenerator-runtime` automatically, by scanning the legacy bundle for `regeneratorRuntime` references here in the code:

https://github.com/alloc/vite-plugin-legacy/blob/9e07f1c26f3288c5743b0248daf8115acbedc35d/src/plugin.ts#L75-L76

It's imported from jsdelivr:

https://github.com/alloc/vite-plugin-legacy/blob/9e07f1c26f3288c5743b0248daf8115acbedc35d/src/plugin.ts#L85

and the import is injected here:

https://github.com/alloc/vite-plugin-legacy/blob/9e07f1c26f3288c5743b0248daf8115acbedc35d/src/plugin.ts#L167

I don't have time to look into this. You should try debugging the Vite process, set a breakpoint at line 76, and see if the check fails. Let me know what you find out. 👍

**Comment by joshdura** [comment]
@aleclarson Awesome, thanks for the info. Will definitely try that!

**Comment by joshdura** [comment]
So after a bit of research it looks like it is definitely bundling `regenerator-runtime`, but is somehow unable to reference it. I am getting an error where `globalThis` is undefined as well, could that be something that would cause issues with this?

**Comment by aleclarson** [comment]
You need to polyfill `globalThis` with either `corejs: true` or `polyfills: ["globalThis"]`. I don't think it's related though.

This is how the `regeneratorRuntime` global is defined:
```js
Function("r","regeneratorRuntime = r")(runtime)
```
Maybe it's incompatible with IE11? Not sure.

Another possibility is that `regenerator-runtime` isn't being executed before the legacy bundle.

**Comment by joshdura** [comment]
I apologize, I just now realized that `vite-plugin-legacy` and `@vitejs/plugin-legacy` are two totally different projects. I am using the latter, and should have checked that before opening this issue.
