### ISSUE TITLE
0.1.4 is not released yet. I can't find it in npm

### ISSUE THREAD

**Issue by anncwb** [alloc/vite-plugin-legacy#3]

**Comment by aleclarson** [comment]
Thanks for the report. This plugin is currently broken anyway, thanks to https://github.com/vitejs/vite/pull/957.

Looking into it...

**Comment by aleclarson** [comment]
Waiting on https://github.com/vitejs/vite/pull/977 to be merged and released

**Comment by aleclarson** [comment]
Published it anyway. You can use `@alloc/vite` until #977 is merged

**Comment by aleclarson** [comment]
v0.1.5 should work with `vite@1.0.0-rc.9`
