### ISSUE TITLE
Legacy bundle not writing to disk

### ISSUE THREAD

**Issue by beezir** [alloc/vite-plugin-legacy#4]
I may be missing an option somewhere, but when I build for production, the legacy js file is never written to disk.   I tested changing the built dist/index.js line that includes bundle.generate to bundle.write and it does successfully write the file once I do that, but I have not figured out how to make that happen without changing that line.

**Comment by aleclarson** [comment]
The plugin is broken since `1.0.0-rc.7`, but it will be fixed in the next release.

More info: https://github.com/alloc/vite-plugin-legacy/issues/3#issuecomment-717928344

**Comment by aleclarson** [comment]
v0.1.5 should work with `vite@1.0.0-rc.9`
