### ISSUE TITLE
Compatible Vite versions

### ISSUE THREAD

**Issue by tonithenhausen** [alloc/vite-plugin-legacy#5]
I have a Vite Vue app and tryed to use your plugin for IE11 support. However, I cannot get it working. I tried Vite versions 1.0.0-rc.6 to 1.0.0-rc.13, but depending on the Vite version either the *.legacy.js is not written to disk or your loader script is not injected into the index.html file.

I have uploaded a sample project to reproduce the issue here: https://github.com/tonithenhausen/vite-plugin-legacy-sample

I am using your version 0.1.4 since your PR to the vite repo has not been accepted yet.

**Comment by aleclarson** [comment]
I'm not sure it works with any official version. I have [my own `vite` fork](https://github.com/aleclarson/vite/commits/master) that works, which is currently based on 1.0.0-rc.13. I'll publish that to `@alloc/vite` on npm sometime soon.

I'll get it working with the official Vite once v2 is released.

**Comment by aleclarson** [comment]
You can now install `vite-plugin-legacy@next` and `vite@next` :)

**Comment by tonithenhausen** [comment]
Thanks and Happy New Year! I will give it a try.
